spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/cinema_test
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=file:db/dbchangelog.xml
