datasource.url=jdbc:h2:./target/test-db/cinema_liquibase_plain;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
datasource.username=sa
datasource.password=
datasource.driver-class-name=org.h2.Driver
spring.liquibase.change-log=file:db/dbchangelog.xml
spring.liquibase.url=${datasource.url}
spring.liquibase.user=${datasource.username}
spring.liquibase.password=${datasource.password}
